---
server_addr: "0.0.0.0:8080"
database_url: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}"
db_pool_size: 5
secret: "${API_SECRET}"
ton_core:
  adnl_port: 30310
  db_path: "/var/ton/ton-wallet-api/data"
  keys_path: "/var/ton/ton-wallet-api/data/adnl-keys.json"
