include:
  - project: 'broxus/trading/infrastructure'
    ref: master
    file: '/gitlab-ci/rust-master.gitlab-ci.yaml'
  - project: 'broxus/trading/infrastructure'
    ref: master
    file: '/gitlab-ci/rust-prod.gitlab-ci.yaml'

deploy:config-master:
  script:
    - |
      deploy/common/build.sh kustomize \
      -t statefulset \
      -r deploy/common/base/service-statefulset.yaml \
      -p deploy/common/base/patch/postgres.yaml \
      -r kustomize/service-http-expose.test.yaml \
      -p deploy/broxus/kustomize/env.test.yaml \
      -p kustomize/overrides.test.yaml \
      > kustomization.yaml

deploy:config-prod:
  script:
    - |
      deploy/common/build.sh kustomize \
      -t statefulset \
      -r deploy/common/base/service-statefulset.yaml \
      -p deploy/common/base/patch/postgres.yaml \
      -r kustomize/service-http-expose.prod.yaml \
      -p deploy/broxus/kustomize/env.prod.yaml \
      -p kustomize/overrides.prod.yaml \
      > kustomization.yaml
