[package]
name = "ton-wallet-api"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
name = "ton_wallet_api_lib"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
aes = "*"
block-modes = "*"
base64 = "*"
chrono = { version = "*", features = ["serde"] }
config = { version = "0.11", default-features = false, features = ["yaml"] }
derive_more = "*"
futures = { version = "0.3" }
rand = "0.7"
hex = "*"
hmac = "*"
http = "0.2"
hyper = { version = "0.14" }
log = { version = "0.4", features = ["std", "serde"] }
log4rs = "1.0"
once_cell = "1.8"
pin-project = "0.4"
opg = { version = "0.0", features = ["uuid"] }
r2d2 = "0.8.9"
reqwest = { version = "0.11", features = ["json"] }
sentry = { version = "0.23.0", features = ["log", "debug-logs"] }
sentry-panic = { version = "0.23.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.17"
sha2 = "*"
snafu = "*"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8", features = ["v4", "serde"] }
url = { version = "2.2.0", features = ["serde"] }
warp = { version = "0.3" }
anyhow = "1.0.38"
lazy_static = "1.4.0"
sqlx = { version = "0.5", features = ["runtime-tokio-native-tls", "postgres", "uuid", "bigdecimal", "offline", "chrono", "json"] }
indexmap = "~1.6.2"
urlencoding = "2.1.0"
ed25519-dalek = { git = "https://github.com/broxus/ed25519-dalek.git" }
external-ip = "4.1.0"
regex = "1.5.4"

thiserror = "1.0.26"
itertools = "0.10.1"
lru = "0.6.5"
parking_lot = { version = "0.11.1", default_features = false }
bigdecimal = {version= "0.2.0",features =["serde"] }
num-bigint = "0.3.2"
num-traits = "0.2.14"

# TON specific dependencies
ton_block = { git = "https://github.com/broxus/ton-labs-block" }
ton_abi = { git = "https://github.com/broxus/ton-labs-abi" }
ton_types = { git = "https://github.com/broxus/ton-labs-types" }

tiny-adnl = { git = "https://github.com/broxus/tiny-adnl" }

# Nekoton SDK
nekoton = { git = "https://github.com/broxus/nekoton.git", default-features = false }
nekoton-abi = { git = "https://github.com/broxus/nekoton.git", features = ["derive"] }
nekoton-utils = { git = "https://github.com/broxus/nekoton.git" }
nekoton-contracts = { git = "https://github.com/broxus/nekoton.git" }

# Indexer engine
ton-indexer = { git = "https://github.com/broxus/ton-indexer.git" }

[dependencies.ton_api]
git = "https://github.com/broxus/ton-labs-tl.git"
branch = "original"
package = "ton_api"
features = ["lite_api", "ton_api"]

[dev-dependencies]
env_logger = "0.8.4"
